// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grtc/grtc.proto

package grtc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import status "google.golang.org/genproto/googleapis/rpc/status"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Routing struct {
	Sequence             int32    `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Routing) Reset()         { *m = Routing{} }
func (m *Routing) String() string { return proto.CompactTextString(m) }
func (*Routing) ProtoMessage()    {}
func (*Routing) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{0}
}
func (m *Routing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Routing.Unmarshal(m, b)
}
func (m *Routing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Routing.Marshal(b, m, deterministic)
}
func (dst *Routing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Routing.Merge(dst, src)
}
func (m *Routing) XXX_Size() int {
	return xxx_messageInfo_Routing.Size(m)
}
func (m *Routing) XXX_DiscardUnknown() {
	xxx_messageInfo_Routing.DiscardUnknown(m)
}

var xxx_messageInfo_Routing proto.InternalMessageInfo

func (m *Routing) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type Request struct {
	Routing *Routing `protobuf:"bytes,1,opt,name=routing,proto3" json:"routing,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Request_Call
	//	*Request_Data
	//	*Request_End
	Type                 isRequest_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

type isRequest_Type interface {
	isRequest_Type()
}

type Request_Call struct {
	Call *Call `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type Request_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Request_End struct {
	End *End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*Request_Call) isRequest_Type() {}

func (*Request_Data) isRequest_Type() {}

func (*Request_End) isRequest_Type() {}

func (m *Request) GetType() isRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Request) GetCall() *Call {
	if x, ok := m.GetType().(*Request_Call); ok {
		return x.Call
	}
	return nil
}

func (m *Request) GetData() *Data {
	if x, ok := m.GetType().(*Request_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Request) GetEnd() *End {
	if x, ok := m.GetType().(*Request_End); ok {
		return x.End
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_Call)(nil),
		(*Request_Data)(nil),
		(*Request_End)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// type
	switch x := m.Type.(type) {
	case *Request_Call:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Call); err != nil {
			return err
		}
	case *Request_Data:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case *Request_End:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.End); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Type has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 2: // type.call
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Call)
		err := b.DecodeMessage(msg)
		m.Type = &Request_Call{msg}
		return true, err
	case 3: // type.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Data)
		err := b.DecodeMessage(msg)
		m.Type = &Request_Data{msg}
		return true, err
	case 4: // type.end
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(End)
		err := b.DecodeMessage(msg)
		m.Type = &Request_End{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// type
	switch x := m.Type.(type) {
	case *Request_Call:
		s := proto.Size(x.Call)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Data:
		s := proto.Size(x.Data)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_End:
		s := proto.Size(x.End)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Response struct {
	Routing *Routing `protobuf:"bytes,1,opt,name=routing,proto3" json:"routing,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Response_Header
	//	*Response_Data
	//	*Response_End
	Type                 isResponse_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

type isResponse_Type interface {
	isResponse_Type()
}

type Response_Header struct {
	Header *Header `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

type Response_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Response_End struct {
	End *End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*Response_Header) isResponse_Type() {}

func (*Response_Data) isResponse_Type() {}

func (*Response_End) isResponse_Type() {}

func (m *Response) GetType() isResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Response) GetHeader() *Header {
	if x, ok := m.GetType().(*Response_Header); ok {
		return x.Header
	}
	return nil
}

func (m *Response) GetData() *Data {
	if x, ok := m.GetType().(*Response_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Response) GetEnd() *End {
	if x, ok := m.GetType().(*Response_End); ok {
		return x.End
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Header)(nil),
		(*Response_Data)(nil),
		(*Response_End)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// type
	switch x := m.Type.(type) {
	case *Response_Header:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Header); err != nil {
			return err
		}
	case *Response_Data:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case *Response_End:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.End); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.Type has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 2: // type.header
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Header)
		err := b.DecodeMessage(msg)
		m.Type = &Response_Header{msg}
		return true, err
	case 3: // type.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Data)
		err := b.DecodeMessage(msg)
		m.Type = &Response_Data{msg}
		return true, err
	case 4: // type.end
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(End)
		err := b.DecodeMessage(msg)
		m.Type = &Response_End{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// type
	switch x := m.Type.(type) {
	case *Response_Header:
		s := proto.Size(x.Header)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Data:
		s := proto.Size(x.Data)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_End:
		s := proto.Size(x.End)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Strings struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Strings) Reset()         { *m = Strings{} }
func (m *Strings) String() string { return proto.CompactTextString(m) }
func (*Strings) ProtoMessage()    {}
func (*Strings) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{3}
}
func (m *Strings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strings.Unmarshal(m, b)
}
func (m *Strings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strings.Marshal(b, m, deterministic)
}
func (dst *Strings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strings.Merge(dst, src)
}
func (m *Strings) XXX_Size() int {
	return xxx_messageInfo_Strings.Size(m)
}
func (m *Strings) XXX_DiscardUnknown() {
	xxx_messageInfo_Strings.DiscardUnknown(m)
}

var xxx_messageInfo_Strings proto.InternalMessageInfo

func (m *Strings) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Metadata struct {
	Md                   map[string]*Strings `protobuf:"bytes,1,rep,name=md,proto3" json:"md,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{4}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetMd() map[string]*Strings {
	if m != nil {
		return m.Md
	}
	return nil
}

type Call struct {
	Method               string    `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{5}
}
func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (dst *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(dst, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Call) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Header struct {
	Metadata             *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{6}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Data struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{7}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type End struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Trailer              *Metadata      `protobuf:"bytes,2,opt,name=trailer,proto3" json:"trailer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *End) Reset()         { *m = End{} }
func (m *End) String() string { return proto.CompactTextString(m) }
func (*End) ProtoMessage()    {}
func (*End) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_947a669eded08020, []int{8}
}
func (m *End) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_End.Unmarshal(m, b)
}
func (m *End) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_End.Marshal(b, m, deterministic)
}
func (dst *End) XXX_Merge(src proto.Message) {
	xxx_messageInfo_End.Merge(dst, src)
}
func (m *End) XXX_Size() int {
	return xxx_messageInfo_End.Size(m)
}
func (m *End) XXX_DiscardUnknown() {
	xxx_messageInfo_End.DiscardUnknown(m)
}

var xxx_messageInfo_End proto.InternalMessageInfo

func (m *End) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *End) GetTrailer() *Metadata {
	if m != nil {
		return m.Trailer
	}
	return nil
}

func init() {
	proto.RegisterType((*Routing)(nil), "grtc.Routing")
	proto.RegisterType((*Request)(nil), "grtc.Request")
	proto.RegisterType((*Response)(nil), "grtc.Response")
	proto.RegisterType((*Strings)(nil), "grtc.Strings")
	proto.RegisterType((*Metadata)(nil), "grtc.Metadata")
	proto.RegisterMapType((map[string]*Strings)(nil), "grtc.Metadata.MdEntry")
	proto.RegisterType((*Call)(nil), "grtc.Call")
	proto.RegisterType((*Header)(nil), "grtc.Header")
	proto.RegisterType((*Data)(nil), "grtc.Data")
	proto.RegisterType((*End)(nil), "grtc.End")
}

func init() { proto.RegisterFile("grtc/grtc.proto", fileDescriptor_grtc_947a669eded08020) }

var fileDescriptor_grtc_947a669eded08020 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4b, 0x8b, 0xdb, 0x30,
	0x10, 0xc7, 0xe3, 0x47, 0x6c, 0x67, 0x92, 0x3e, 0xd0, 0x21, 0x35, 0x86, 0x42, 0xea, 0xd2, 0x34,
	0xf4, 0xe0, 0x40, 0xda, 0x43, 0xe9, 0xb1, 0x4d, 0xc0, 0x14, 0x72, 0x51, 0x8f, 0x3d, 0xa9, 0x96,
	0x70, 0x42, 0x6d, 0xd9, 0x95, 0xe4, 0xb2, 0xf9, 0x30, 0x7b, 0xdb, 0x0f, 0xba, 0xe8, 0x91, 0xb0,
	0xbb, 0xa7, 0x5d, 0xd8, 0x8b, 0xd1, 0xe8, 0xf7, 0xd7, 0xcc, 0x5f, 0x33, 0x32, 0xbc, 0xaa, 0x85,
	0xaa, 0xd6, 0xfa, 0x53, 0xf4, 0xa2, 0x53, 0x1d, 0x0a, 0xf5, 0x3a, 0x7b, 0x53, 0x77, 0x5d, 0xdd,
	0xb0, 0xb5, 0xe8, 0xab, 0xb5, 0x54, 0x44, 0x0d, 0xd2, 0xe2, 0xfc, 0x03, 0xc4, 0xb8, 0x1b, 0xd4,
	0x91, 0xd7, 0x28, 0x83, 0x44, 0xb2, 0x7f, 0x03, 0xe3, 0x15, 0x4b, 0xbd, 0x85, 0xb7, 0x1a, 0xe3,
	0x4b, 0x9c, 0x5f, 0x7b, 0x10, 0x63, 0x1d, 0x48, 0x85, 0x3e, 0x42, 0x2c, 0xec, 0x11, 0x23, 0x9b,
	0x6e, 0x5e, 0x14, 0xa6, 0x9e, 0xcb, 0x83, 0xcf, 0x14, 0x2d, 0x20, 0xac, 0x48, 0xd3, 0xa4, 0xbe,
	0x51, 0x81, 0x55, 0xfd, 0x20, 0x4d, 0x53, 0x8e, 0xb0, 0x21, 0x5a, 0x41, 0x89, 0x22, 0x69, 0x70,
	0x57, 0xb1, 0x25, 0x8a, 0x68, 0x85, 0x26, 0xe8, 0x2d, 0x04, 0x8c, 0xd3, 0x34, 0x34, 0x82, 0x89,
	0x15, 0xec, 0x38, 0x2d, 0x47, 0x58, 0xef, 0x7f, 0x8f, 0x20, 0x54, 0xa7, 0x9e, 0xe5, 0x37, 0x1e,
	0x24, 0x98, 0xc9, 0xbe, 0xe3, 0x92, 0x3d, 0xde, 0xe0, 0x12, 0xa2, 0x03, 0x23, 0x94, 0x09, 0x67,
	0x71, 0x66, 0x75, 0xa5, 0xd9, 0x2b, 0x47, 0xd8, 0xd1, 0xe7, 0xb3, 0xf9, 0x0e, 0xe2, 0x5f, 0x4a,
	0x1c, 0x79, 0x2d, 0xd1, 0x1c, 0xa2, 0xff, 0xa4, 0x19, 0x98, 0x4c, 0xbd, 0x45, 0xb0, 0x9a, 0x60,
	0x17, 0xe5, 0x57, 0x90, 0xec, 0x99, 0x22, 0x26, 0xeb, 0x12, 0xfc, 0x96, 0x1a, 0x3e, 0xdd, 0xcc,
	0x6d, 0xd2, 0x33, 0x2b, 0xf6, 0x74, 0xc7, 0x95, 0x38, 0x61, 0xbf, 0xa5, 0xd9, 0x16, 0x62, 0x17,
	0xa2, 0xd7, 0x10, 0xfc, 0x65, 0x27, 0x73, 0xef, 0x09, 0xd6, 0x4b, 0xf4, 0x1e, 0xc6, 0x26, 0xb5,
	0xbb, 0xa3, 0xeb, 0x85, 0xb3, 0x81, 0x2d, 0xfb, 0xe6, 0x7f, 0xf5, 0xf2, 0x9f, 0x10, 0xea, 0xe1,
	0x68, 0x67, 0x2d, 0x53, 0x87, 0x8e, 0xba, 0x2c, 0x2e, 0x42, 0x9f, 0x20, 0x69, 0x5d, 0x75, 0x97,
	0xeb, 0xe5, 0x7d, 0x4f, 0xf8, 0xc2, 0xf3, 0x2f, 0x10, 0xd9, 0x2e, 0x3e, 0xe9, 0x54, 0x06, 0xa1,
	0xee, 0x2a, 0x42, 0xae, 0xdf, 0xba, 0xfe, 0xcc, 0x76, 0x38, 0xff, 0x0d, 0xc1, 0x8e, 0x6b, 0x13,
	0x91, 0x7d, 0xbf, 0x6e, 0xb4, 0xa8, 0xb0, 0x2f, 0xbb, 0x10, 0xbd, 0xbe, 0x94, 0x26, 0xd8, 0x29,
	0xd0, 0x0a, 0x62, 0x25, 0xc8, 0xb1, 0xb9, 0xcc, 0xf7, 0x61, 0xe5, 0x33, 0xfe, 0x13, 0x99, 0x9f,
	0xe1, 0xf3, 0x6d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xdb, 0xf3, 0x0f, 0x3e, 0x03, 0x00, 0x00,
}
