// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grtc/grtc.proto

package grtc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import status "google.golang.org/genproto/googleapis/rpc/status"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Routing struct {
	Sequence             int32    `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Routing) Reset()         { *m = Routing{} }
func (m *Routing) String() string { return proto.CompactTextString(m) }
func (*Routing) ProtoMessage()    {}
func (*Routing) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_ed406bc7999ce871, []int{0}
}
func (m *Routing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Routing.Unmarshal(m, b)
}
func (m *Routing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Routing.Marshal(b, m, deterministic)
}
func (dst *Routing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Routing.Merge(dst, src)
}
func (m *Routing) XXX_Size() int {
	return xxx_messageInfo_Routing.Size(m)
}
func (m *Routing) XXX_DiscardUnknown() {
	xxx_messageInfo_Routing.DiscardUnknown(m)
}

var xxx_messageInfo_Routing proto.InternalMessageInfo

func (m *Routing) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type Request struct {
	Routing *Routing `protobuf:"bytes,1,opt,name=routing,proto3" json:"routing,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Request_Call
	//	*Request_Data
	//	*Request_End
	Type                 isRequest_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_ed406bc7999ce871, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

type isRequest_Type interface {
	isRequest_Type()
}

type Request_Call struct {
	Call *Call `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type Request_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Request_End struct {
	End *End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*Request_Call) isRequest_Type() {}

func (*Request_Data) isRequest_Type() {}

func (*Request_End) isRequest_Type() {}

func (m *Request) GetType() isRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Request) GetCall() *Call {
	if x, ok := m.GetType().(*Request_Call); ok {
		return x.Call
	}
	return nil
}

func (m *Request) GetData() *Data {
	if x, ok := m.GetType().(*Request_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Request) GetEnd() *End {
	if x, ok := m.GetType().(*Request_End); ok {
		return x.End
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_Call)(nil),
		(*Request_Data)(nil),
		(*Request_End)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// type
	switch x := m.Type.(type) {
	case *Request_Call:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Call); err != nil {
			return err
		}
	case *Request_Data:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case *Request_End:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.End); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Type has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 2: // type.call
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Call)
		err := b.DecodeMessage(msg)
		m.Type = &Request_Call{msg}
		return true, err
	case 3: // type.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Data)
		err := b.DecodeMessage(msg)
		m.Type = &Request_Data{msg}
		return true, err
	case 4: // type.end
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(End)
		err := b.DecodeMessage(msg)
		m.Type = &Request_End{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// type
	switch x := m.Type.(type) {
	case *Request_Call:
		s := proto.Size(x.Call)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Data:
		s := proto.Size(x.Data)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_End:
		s := proto.Size(x.End)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Response struct {
	Routing *Routing `protobuf:"bytes,1,opt,name=routing,proto3" json:"routing,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Response_Data
	//	*Response_End
	Type                 isResponse_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_ed406bc7999ce871, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRouting() *Routing {
	if m != nil {
		return m.Routing
	}
	return nil
}

type isResponse_Type interface {
	isResponse_Type()
}

type Response_Data struct {
	Data *Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type Response_End struct {
	End *End `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*Response_Data) isResponse_Type() {}

func (*Response_End) isResponse_Type() {}

func (m *Response) GetType() isResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Response) GetData() *Data {
	if x, ok := m.GetType().(*Response_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Response) GetEnd() *End {
	if x, ok := m.GetType().(*Response_End); ok {
		return x.End
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Data)(nil),
		(*Response_End)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// type
	switch x := m.Type.(type) {
	case *Response_Data:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case *Response_End:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.End); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.Type has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 2: // type.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Data)
		err := b.DecodeMessage(msg)
		m.Type = &Response_Data{msg}
		return true, err
	case 3: // type.end
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(End)
		err := b.DecodeMessage(msg)
		m.Type = &Response_End{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// type
	switch x := m.Type.(type) {
	case *Response_Data:
		s := proto.Size(x.Data)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_End:
		s := proto.Size(x.End)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Call struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_ed406bc7999ce871, []int{3}
}
func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (dst *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(dst, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type Data struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_ed406bc7999ce871, []int{4}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type End struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *End) Reset()         { *m = End{} }
func (m *End) String() string { return proto.CompactTextString(m) }
func (*End) ProtoMessage()    {}
func (*End) Descriptor() ([]byte, []int) {
	return fileDescriptor_grtc_ed406bc7999ce871, []int{5}
}
func (m *End) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_End.Unmarshal(m, b)
}
func (m *End) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_End.Marshal(b, m, deterministic)
}
func (dst *End) XXX_Merge(src proto.Message) {
	xxx_messageInfo_End.Merge(dst, src)
}
func (m *End) XXX_Size() int {
	return xxx_messageInfo_End.Size(m)
}
func (m *End) XXX_DiscardUnknown() {
	xxx_messageInfo_End.DiscardUnknown(m)
}

var xxx_messageInfo_End proto.InternalMessageInfo

func (m *End) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Routing)(nil), "grtc.Routing")
	proto.RegisterType((*Request)(nil), "grtc.Request")
	proto.RegisterType((*Response)(nil), "grtc.Response")
	proto.RegisterType((*Call)(nil), "grtc.Call")
	proto.RegisterType((*Data)(nil), "grtc.Data")
	proto.RegisterType((*End)(nil), "grtc.End")
}

func init() { proto.RegisterFile("grtc/grtc.proto", fileDescriptor_grtc_ed406bc7999ce871) }

var fileDescriptor_grtc_ed406bc7999ce871 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0xf4, 0x30,
	0x10, 0xc7, 0xb7, 0xdb, 0x7c, 0xed, 0xee, 0x7c, 0x8a, 0x30, 0x07, 0x2d, 0x05, 0x65, 0x29, 0x88,
	0xe2, 0xa1, 0x45, 0x7d, 0x03, 0x75, 0x61, 0xcf, 0xf1, 0x09, 0x62, 0x1b, 0xaa, 0x50, 0x93, 0xda,
	0x4c, 0x0f, 0x82, 0xaf, 0xe2, 0xbb, 0xca, 0x24, 0x51, 0xbc, 0x2d, 0x5e, 0x4a, 0x27, 0xff, 0x5f,
	0xe6, 0x37, 0x61, 0xe0, 0xa8, 0x9f, 0xa8, 0x6d, 0xf8, 0x53, 0x8f, 0x93, 0x25, 0x8b, 0x82, 0xff,
	0xcb, 0x93, 0xde, 0xda, 0x7e, 0xd0, 0xcd, 0x34, 0xb6, 0x8d, 0x23, 0x45, 0xb3, 0x0b, 0x71, 0x75,
	0x0e, 0xb9, 0xb4, 0x33, 0xbd, 0x98, 0x1e, 0x4b, 0x58, 0x39, 0xfd, 0x36, 0x6b, 0xd3, 0xea, 0x22,
	0xd9, 0x24, 0x97, 0xff, 0xe4, 0x4f, 0x5d, 0x7d, 0x26, 0x90, 0x4b, 0x2e, 0x1c, 0xe1, 0x05, 0xe4,
	0x53, 0xb8, 0xe2, 0xb1, 0xff, 0x37, 0x87, 0xb5, 0xf7, 0xc5, 0x3e, 0xf2, 0x3b, 0xc5, 0x0d, 0x88,
	0x56, 0x0d, 0x43, 0xb1, 0xf4, 0x14, 0x04, 0xea, 0x5e, 0x0d, 0xc3, 0x6e, 0x21, 0x7d, 0xc2, 0x44,
	0xa7, 0x48, 0x15, 0xe9, 0x6f, 0xe2, 0x41, 0x91, 0x62, 0x82, 0x13, 0x3c, 0x85, 0x54, 0x9b, 0xae,
	0x10, 0x1e, 0x58, 0x07, 0x60, 0x6b, 0xba, 0xdd, 0x42, 0xf2, 0xf9, 0x5d, 0x06, 0x82, 0xde, 0x47,
	0x5d, 0x7d, 0xc0, 0x4a, 0x6a, 0x37, 0x5a, 0xe3, 0xf4, 0x9f, 0xe6, 0xf3, 0xf6, 0xe5, 0x3e, 0x7b,
	0xba, 0xc7, 0x7e, 0x06, 0x82, 0x9f, 0x85, 0xc7, 0x90, 0xbd, 0x6a, 0x7a, 0xb6, 0x9d, 0x17, 0xaf,
	0x65, 0xac, 0xaa, 0x12, 0x04, 0xb7, 0x45, 0x8c, 0x42, 0x4e, 0x0f, 0x82, 0xa2, 0xba, 0x86, 0x74,
	0x6b, 0x3a, 0xbc, 0x82, 0x2c, 0xec, 0x25, 0xce, 0x8c, 0x75, 0xd8, 0x58, 0x3d, 0x8d, 0x6d, 0xfd,
	0xe8, 0x13, 0x19, 0x89, 0xa7, 0xcc, 0xaf, 0xee, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x12, 0x92,
	0xe6, 0xba, 0xec, 0x01, 0x00, 0x00,
}
